name: 'OpenSurplusManager'
description: 'OpenSurplusManager add-on'
version: 'v0.1.8.1-beta'
slug: 'open_surplus_manager'
init: false
image: 'ghcr.io/josermorales/opensurplusmanager'
url: https://github.com/JoseRMorales/OpenSurplusManager
arch:
  - amd64
ports:
  8080/tcp: 8080
environment:
  CONFIG_FILE: /config/osm.yaml
map:
  - addon_config:rw
